version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: negocio_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nueva_pass_123  
      POSTGRES_DB: negocio_analitica
    ports:
      - "5440:5432"                     
    volumes:
      - postgres_data:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: negocio_bi
    restart: always
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_app_db
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: nueva_pass_123         
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    volumes:
      - metabase_data:/metabase-data


volumes:
  postgres_data:
  metabase_data: